### PR TITLE
Upgrading to the latest version of Jupyter-Book

### PR DESCRIPTION
**Pull request by balajialg**

### CODE REVIEW

**Comment by choldgraf** [comment]
This commit fixed the `_toc.yml` file: https://github.com/balajialg/curriculum-guide/commit/c5763c32702b060811f6cf99e35ed6a465237ab6

The problem was that it was not a correctly-formatted file, that's why you weren't getting the right output

**Comment by balajialg** [comment]
@choldgraf Thanks a ton, Chris! Appreciate fixing the TOC file. 

However, some of the files are still not linked to the HTML output. I will spend some time troubleshooting this today. If I am not able to fix it, I will probably park this upgrade for some more time.

**Comment by choldgraf** [comment]
did this one get resolved? if it still doesn't work what do you say we just time-box 30 minutes to work together to try and fix this, and if we can't then put it on the backlog for later?

**Comment by balajialg** [comment]
Hi @choldgraf, It seems to work after I tweaked the _config file a bit. Here is the dummy [link](https://balajialg.github.io/curriculum-guide/intro.html). However, some of the formatting from the old website is not getting replicated in the upgraded book. I do have few questions which I would love to get your perspective on. Do you think that is the best use of your time?

I was thinking of writing about some of the mistakes that I made as a newbie upgrading books, which should have been avoided. that may appeal to a new non-developer audience that might use books. Do you think that will be useful for other members in the community?

**Comment by choldgraf** [comment]
@balajialg that sounds great, if you'd like I'd be happy to do a debrief with you :-)

**Comment by balajialg** [comment]
@choldgraf awesome will set up some time with you next week!

**Pull request closed without merging**
